### ISSUE TITLE
ETA for code release?

### ISSUE THREAD

**Issue by oscarqht** [xingyi-li/3d-cinemagraphy#2]
Hi, thanks for this amazing work and I really can't wait to try this out!! Is there an estimated date for the code release? Thanks a lot :)

**Comment by zcdliuwei** [comment]
+1

**Comment by jyuan-dev** [comment]
+1

**Comment by EyalLTX** [comment]
+1 😀

**Comment by WPU93** [comment]
+1

**Comment by dlutzzw** [comment]
+1

**Comment by xiong224** [comment]
+1

**Comment by lofrienger** [comment]
+1

**Comment by bojin-nwafu** [comment]
+1

**Comment by TristaCheng2018** [comment]
+1

**Comment by AlanLiangC** [comment]
+1 😀

**Comment by J3698** [comment]
+1

**Comment by ARTUROSING** [comment]
I am also waiting for the release, but it seems that the author does not plan to publish the source code.

**Comment by xingyi-li** [comment]
Dear all, thanks for your interest. I will release the code as soon as possible, maybe in June.
