### ISSUE TITLE
Two questions regarding the code

### ISSUE THREAD

**Issue by Amazingren** [xingyi-li/3d-cinemagraphy#3]
Hi @xingyi-li,

Thanks for the impressive work and the released code.

I have two questions regarding the codes:

- 1. Is it possible to release the training code of the proposed method?
- 2. For the baseline method[19: Animating pictures with eulerian motion fields]. It seems the author didn't release the code as well, how to get the corresponding results of [19]?

Best regards and thanks in advance,

**Comment by xingyi-li** [comment]
Hi @Amazingren,

Thanks for your interest!

i) We currently don't plan to release the training code. We are sorry for any inconvenience caused.
ii) Indeed, the authors of [19] did not release the code for their paper. We refer to [SLR-SFS](https://github.com/simon3dv/SLR-SFS) and reimplement the baseline method. It is interesting to note that, we cannot fully reproduce the results demonstrated in [19]. This made us believe that the task of predicting optical flow from a single image is highly uncertain and challenging. To achieve better motion estimation results, we were inspired by recent papers on controllable motion estimation and incorporated hints and masks to assist the motion estimation module, which we believe, can reduce the difficulty of optical flow prediction. In this way, we can obtain relatively satisfactory results and controllable animation. As a result, when implementing our framework, for in-the-wild photos, we used the controllable motion estimation module as our motion estimation network. Maybe predicting accurate optical flow from just a single RGB image can be done when we train with more data.

Regards,
Xingyi

**Comment by Amazingren** [comment]
> Hi @Amazingren,
> 
> Thanks for your interest!
> 
> i) We currently don't plan to release the training code. We are sorry for any inconvenience caused. ii) Indeed, the authors of [19] did not release the code for their paper. We refer to [SLR-SFS](https://github.com/simon3dv/SLR-SFS) and reimplement the baseline method. It is interesting to note that, we cannot fully reproduce the results demonstrated in [19]. This made us believe that the task of predicting optical flow from a single image is highly uncertain and challenging. To achieve better motion estimation results, we were inspired by recent papers on controllable motion estimation and incorporated hints and masks to assist the motion estimation module, which we believe, can reduce the difficulty of optical flow prediction. In this way, we can obtain relatively satisfactory results and controllable animation. As a result, when implementing our framework, for in-the-wild photos, we used the controllable motion estimation module as our motion estimation network. Maybe predicting accurate optical flow from just a single RGB image can be done when we train with more data.
> 
> Regards, Xingyi

thanks a lot for the reply. And it helps a lot for me about the [19].

Bests regards and many thanks!
